### PR TITLE
Adding fix for sitemap issues

### PR DESCRIPTION
**Pull request by sublibra**
In progress

### CODE REVIEW

**Comment by qlikossbuild** [comment]
Deploy preview for *qlikcore* ready!

Built with commit 1c8e600045e27eccccc9507a8b140762f42c94d5

https://deploy-preview-392--qlikcore.netlify.com

**Comment by sublibra** [comment]
@reviewers. Good enough? Doesn't work locally but seems to be ok by manual test of deploy preview. See commit message for background

**Comment by sublibra** [comment]
Yes. Loads of issues generating the pages when doing so. Need to know if we have done other customization as well.

**Comment by aihazm** [comment]
@sublibra this code change will actuall fix the sitemap!
=> https://deploy-preview-392--qlikcore.netlify.com/sitemap.xml
vs. https://qlikcore.com/sitemap.xml

in master the URL tags looks like this 
```
<url>
<loc>None</loc>
<lastmod>2018-09-07</lastmod>
<changefreq>daily</changefreq>
</url>
```

**Pull request merged**
