### PR TITLE
Added site_url

### PR DESCRIPTION
**Pull request by janmiderback**
Fixes so that clicking on the logo takes you the main https://qlikcore.com page.

### CODE REVIEW

**Comment by qlikossbuild** [comment]
Deploy preview for *qlikcore* ready!

Built with commit 9e844b9c71a68bfcfcab4435dffa1eb212c2d806

https://deploy-preview-384--qlikcore.netlify.com

**Comment by janmiderback** [comment]
Closes #382

**Comment by peol** [comment]
This breaks preview deployments (e.g. the netlify link above), is it not possible to have site_url to `/` only?

**Comment by janmiderback** [comment]
@peol Yes, I know it breaks the preview but did not consider it to be a blocker for this.
Setting site_url to qlikcore.com seems more correct than /, in a way, but I'll check if just / works.

**Comment by janmiderback** [comment]
Nope, just `/` is not accepted by mkdocs.
So the question is if we can stick to the solution and live with that clicking on the logo on a preview site actually takes you to the live site. I would say it is ok. What you think?

**Comment by janmiderback** [comment]
Seems like @hrigner fixed it in https://github.com/qlik-oss/core-website/pull/385 where it works on both preview and (hopefully) on live. Then we can discard this.

**Comment by janmiderback** [comment]
Obsolete

**Pull request closed without merging**
