### PR TITLE
Document the ScriptLogVerbosity command line parameter

### LINKED ISSUE #435: Add information about core data reloading
Add information about what is logged and when during reloads (verbosity, where to findlogging data, ...)

### PR DESCRIPTION
**Pull request by wennmo**
This closes #435

### CODE REVIEW

**Comment by qlikossbuild** [comment]
Deploy preview for *core-website* ready!

Built with commit 7180a27cc63439428f3c96995f75a702e158ef0c

https://deploy-preview-453--core-website.netlify.com

**Comment by wennmo** [comment]
Is there some other way we should document this flag? I have enabled it in the `core-data-loading` docker-compose as well.

**Comment by wennmo** [comment]
I was thinking if we should add it to the core-data-loading [tutorials](https://github.com/qlik-oss/core-website/tree/master/docs/tutorials/data-loading)

**Comment by sublibra** [comment]
Last changes looking good to me!

**Pull request merged**
