### PR TITLE
Updates for the new hello-data-halyard example

### PR DESCRIPTION
**Pull request by janmiderback**

### CODE REVIEW

**Comment by qlikossbuild** [comment]
Deploy preview for *qlikcore* ready!

Built with commit b8e114b21c9cae330bd47cbb0c10fed0482b288e

https://deploy-preview-369--qlikcore.netlify.com

**Comment by peol** [comment]
Perhaps add @kyleweishaar as reviewer so he can go through it once he has the time to do so.

**Comment by janmiderback** [comment]
@kyleweishaar PTAL when you have time.

**Comment by janmiderback** [comment]
Closes #368

**Pull request merged**
