### PR TITLE
Adding early draft of tooling section

### LINKED ISSUE #427: Add corectl documenation to qlik core website
Describe tool usage

* why
* what
* how (the tool is used)

### PR DESCRIPTION
**Pull request by sublibra**
Adding a suggestion on how to setup a tooling section on the site. The idea is to provide a top level reason for the tool's existence (use cases) not a documentation of the tool (that should go in the repo). 

Focus on background and structure first, I will look into the text later.

Thoughts to reflect upon
- Should we have a separate tooling chapter or should this go as part of download (I prefer not)
- Is this a good scope? Does it help the users

Fixes #427

### CODE REVIEW

**Comment by qlikossbuild** [comment]
Deploy preview for *core-website* ready!

Built with commit 5def69c22b895f8b3be0f92aeb570fe115e7732c

https://deploy-preview-439--core-website.netlify.com

**Comment by hrigner** [comment]
I agree on having the tools on the page that today is called downloads would be nicer!

**Comment by JohanBjerning** [comment]
Agree, but where do we then put the documentation about the tools? E.g. https://deploy-preview-439--core-website.netlify.com/tooling/corectl/

**Comment by peol** [comment]
There's a larger revamp I'd like for us to do with the results of the research project later. So let's merge this now, and fix the Downloads page (split into three tables: "Services", "Tooling", "Libraries") right now, and do the bigger revamp in Q1-ish.

**Pull request closed without merging**
