### PR TITLE
Using google analytics tag manager

### LINKED ISSUE #462: Replace OOTB Google Analytics with Tag Manager
Material for MKDocs supports what's called "classic google analytics" but we should move to "google analytics tag manager" instead. We need to override the MKDocs partial for analytics and use this script **instead** of the existing one:

```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-P7VJSX');</script>
<!-- End Google Tag Manager -->


<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-P7VJSX"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```

`GTM-P7VJSX` here is the tracking code and should be fetched from the MKDocs config instead.

Resources:

https://squidfunk.github.io/mkdocs-material/getting-started/#google-analytics
https://github.com/squidfunk/mkdocs-material/blob/65ab9fa0181a43e26b701df490fbdf4774b280af/src/partials/integrations/analytics.html#L42

### PR DESCRIPTION
**Pull request by hrigner**
Closes #462

### CODE REVIEW

**Comment by qlikossbuild** [comment]
Deploy preview for *core-website* ready!

Built with commit 1d7afae1aa029084c4d1a97767ee326daac38b95

https://deploy-preview-467--core-website.netlify.com

**Comment by peol** [comment]
@TRB3269 I see a lot of weird network traffic when enabled, is this really normal? Looks pretty creepy to me (all traffic below google tag manager) :/

screenshot 2018-12-19 at 15 12 19

**Comment by TRB3269** [comment]
Copying in Abhi on this but think it’s pretty typical. Abhi — can you please confirm?

And some of what’s below is attached to the Marketo form we have for the evaluation trial.

Tracy Russell-Beck, MBA
Developer Marketing Manager

Mobile: +1 919-618-1540
Skype: tracy.g.russell
Email:  Tracy.Russell-Beck@qlik.com<mailto:Tracy.Russell-Beck@qlik.com>

Qlik
5440 Wade Park Blvd
Suite 400
Raleigh North Carolina 27607

qlik.com<http://www.qlik.com/>

The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this in error, please contact the sender and delete the material from any computer.

**Comment by TRB3269** [comment]
Hi,

Yes this traffic is okay.

  1.  Gtm.js = this is Google Tag Manager’s container javascript
  2.  Analytics.js = Google Analytics tracking script
  3.  Munchkin = This is our Marketo tracking script (Marketing Automation)
  4.  Demandbase = This is our Account Based Marketing(ABM) tool’s script
  5.  LinkId.js = Part of Google Analytics script which allows us to track all the Qlik.com websites in one session. I.e. doesn’t create a new cookie/sessionID while traversing b/w websites


Can you let me know the Dev/QA url where you’ve implemented this script please ?

Abhishek Bhatla
Web Analytics Manager

Email:  Abhishek.Bhatla@qlik.com

Qlik
150 N. Radnor Chester Road
Suite E 120
Radnor Pennsylvania 19087

qlik.com<http://www.qlik.com/>

The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this in error, please contact the sender and delete the material from any computer.

**Comment by TRB3269** [comment]
Thanks, Abhi. Here’s the link:

deploy-preview-467--core-website.netlify.com

Tracy Russell-Beck, MBA
Developer Marketing Manager

Mobile: +1 919-618-1540
Skype: tracy.g.russell
Email:  Tracy.Russell-Beck@qlik.com<mailto:Tracy.Russell-Beck@qlik.com>

Qlik
5440 Wade Park Blvd
Suite 400
Raleigh North Carolina 27607

qlik.com<http://www.qlik.com/>

The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this in error, please contact the sender and delete the material from any computer.


From: Abhishek Bhatla <Abhishek.Bhatla@qlik.com>
Date: Wednesday, December 19, 2018 at 1:49 PM
To: Tracy Russell-Beck <Tracy.Russell-Beck@qlik.com>, qlik-oss/core-website <reply@reply.github.com>, qlik-oss/core-website <core-website@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [qlik-oss/core-website] Using google analytics tag manager (#467)

Hi,

Yes this traffic is okay.

  1.  Gtm.js = this is Google Tag Manager’s container javascript
  2.  Analytics.js = Google Analytics tracking script
  3.  Munchkin = This is our Marketo tracking script (Marketing Automation)
  4.  Demandbase = This is our Account Based Marketing(ABM) tool’s script
  5.  LinkId.js = Part of Google Analytics script which allows us to track all the Qlik.com websites in one session. I.e. doesn’t create a new cookie/sessionID while traversing b/w websites


Can you let me know the Dev/QA url where you’ve implemented this script please ?

Abhishek Bhatla
Web Analytics Manager

Email:  Abhishek.Bhatla@qlik.com

Qlik
150 N. Radnor Chester Road
Suite E 120
Radnor Pennsylvania 19087

qlik.com<http://www.qlik.com/>

The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this in error, please contact the sender and delete the material from any computer.

**Comment by peol** [comment]
Thanks for the clarifications! I'm OK with the changes in this PR.

@TRB3269 so if you guys see that it's working properly on your end let us know so that we can merge this into core.qlik.com.

**Comment by TRB3269** [comment]
@peol -- looks like the code was added to the footer of the website. Could you please move it to the header?

**Comment by peol** [comment]
@TRB3269 That would require us to override an additional template. The script is created using the `async` tag: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-async so it don't see how moving it would make a difference? :)

**Comment by TRB3269** [comment]
@peol -- the drawback of putting it the footer is that some of the tags may not fire correctly. The header executes first, so that's why we recommend adding it to the header so that at least we capture the hits/traffic accurately. 

https://stackoverflow.com/questions/10712908/google-analytics-in-header-or-footer

**Pull request merged**
